update bash script and config create
Signed-off-by: navendu-pottekkat <navendupottekkat@gmail.com>

diff --git a/meshery b/meshery
--- a/meshery
+++ b/meshery
@@ -14,31 +14,48 @@
 
 #!/usr/bin/env bash
 
-# DEFAULT PLATFORM
-PLATFORM="docker"
-
+# Get the platform to deploy Meshery from the flag
 while getopts ":p:" opt; do
-  case $opt in
-  p)
-    case $OPTARG in
-    docker)
-      PLATFORM="docker"
-      ;;
-    kubernetes)
-      PLATFORM="kubernetes"
-      ;;
+    case $opt in
+    p)
+        case $OPTARG in
+        docker)
+            PLATFORM="docker"
+            ;;
+        kubernetes)
+            PLATFORM="kubernetes"
+            ;;
+        *)
+            echo "Invalid platform: $OPTARG"
+            exit 1
+            ;;
+        esac
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$OPTARG requires a platform argument." >&2
+        exit 1
+        ;;
     esac
-    ;;
-  \?)
-    echo "Invalid option: -$OPTARG" >&2
-    exit 1
-    ;;
-  :)
-    echo "Option -$OPTARG requires a platform argument." >&2
-    exit 1
-    ;;
-  esac
 done
+
+# If no flag is present, prompt the user for a platform
+if [ ! "$PLATFORM" ]; then
+    echo Enter a platform to deploy Meshery. Available platforms [docker, kubernetes]:
+    read PLATFORM
+fi
+
+case "$PLATFORM" in
+docker | kubernetes) ;;
+
+*)
+    echo "Invalid platform: $PLATFORM"
+    exit 1
+    ;;
+esac
 
 ####### COMMON FUNCTIONS
 ############################
