Added custom context support in installer, user can now download only required adapters
Signed-off-by: Devansh Gupta <devanshguptamrt@gmail.com>

diff --git a/meshery b/meshery
--- a/meshery
+++ b/meshery
@@ -1,4 +1,4 @@
-# Copyright 2019 Layer5 Authors
+i# Copyright 2019 Layer5 Authors
 #
 #   Licensed under the Apache License, Version 2.0 (the "License");
 #   you may not use this file except in compliance with the License.
@@ -17,27 +17,27 @@
 # Get the platform to deploy Meshery from the flag
 while getopts ":p:" opt; do
     case $opt in
-    p)
-        case $OPTARG in
-        docker)
-            PLATFORM="docker"
-            ;;
-        kubernetes)
-            PLATFORM="kubernetes"
-            ;;
-        *)
-            echo "Invalid platform: $OPTARG"
+        p)
+            case $OPTARG in
+                docker)
+                    PLATFORM="docker"
+                ;;
+                kubernetes)
+                    PLATFORM="kubernetes"
+                ;;
+                *)
+                    echo "Invalid platform: $OPTARG"
+                    exit 1
+                ;;
+            esac
+        ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
             exit 1
-            ;;
-        esac
         ;;
-    \?)
-        echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-    :)
-        echo "Option -$OPTARG requires a platform argument." >&2
-        exit 1
+        :)
+            echo "Option -$OPTARG requires a platform argument." >&2
+            exit 1
         ;;
     esac
 done
@@ -49,11 +49,11 @@ if [ ! "$PLATFORM" ]; then
 fi
 
 case "$PLATFORM" in
-docker | kubernetes) ;;
-
-*)
-    echo "Invalid platform: $PLATFORM"
-    exit 1
+    docker | kubernetes) ;;
+    
+    *)
+        echo "Invalid platform: $PLATFORM"
+        exit 1
     ;;
 esac
 
@@ -70,9 +70,9 @@ OSARCHITECTURE="$(uname -m)"
 OS="$(uname)"
 
 if [ "x${OS}" = "xDarwin" ] ; then
-  OSEXT="Darwin"
+    OSEXT="Darwin"
 else
-  OSEXT="Linux"
+    OSEXT="Linux"
 fi
 
 #######   PREFLIGHT CHECK
@@ -84,14 +84,14 @@ if ! command_exists curl ; then
 fi
 
 if [ "x${MESHERY_VERSION}" = "x" ] ; then
-  MESHERY_VERSION=$(curl -L -s https://api.github.com/repos/meshery/meshery/releases | \
-                  grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | \
-                  grep -v "rc\.[0-9]$"| head -n 1 )
+    MESHERY_VERSION=$(curl -L -s https://api.github.com/repos/meshery/meshery/releases | \
+    grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | \
+grep -v "rc\.[0-9]$"| head -n 1 )
 fi
 
 if [ "x${MESHERY_VERSION}" = "x" ] ; then
-  printf "Unable to get latest mesheryctl version. Set MESHERY_VERSION env var and re-run. For example: export MESHERY_VERSION=v0.1.6\n"
-  exit;
+printf "Unable to get latest mesheryctl version. Set MESHERY_VERSION env var and re-run. For example: export MESHERY_VERSION=v0.1.6\n"
+exit;
 fi
 
 NAME="mesheryctl-${MESHERY_VERSION}"
@@ -102,21 +102,21 @@ curl -L ${URL} -o ${PWD}/meshery.zip
 
 validFile=`file ${PWD}/meshery.zip | grep 'Zip archive data'`
 if [ -z "$validFile" ] ; then
-  printf "Unable to get latest meshery install package. Set MESHERY_VERSION env var and re-run. For example: export MESHERY_VERSION=v0.1.6\n"
-  exit;
+printf "Unable to get latest meshery install package. Set MESHERY_VERSION env var and re-run. For example: export MESHERY_VERSION=v0.1.6\n"
+exit;
 fi
 
 # Generate a temporary folder to store intermediate installation files
 temporary_dir_name=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)
 if [ -z "$temporary_dir_name" ] ; then
-   temporary_dir_name="temp_extract_dir"
+temporary_dir_name="temp_extract_dir"
 fi
 
 mkdir $temporary_dir_name
 if [ $? -ne 0 ] ; then
-  rm ${PWD}/meshery.zip
-  printf "Disk space is low on the system, Re-try installation after cleaning up some files.\n"
-  exit 1;
+rm ${PWD}/meshery.zip
+printf "Disk space is low on the system, Re-try installation after cleaning up some files.\n"
+exit 1;
 fi
 
 printf "\nExtracting %s to temporary folder %s...\n" "$NAME" "$temporary_dir_name"
@@ -127,42 +127,77 @@ unzip ${PWD}/meshery.zip -d ${PWD}/$temporary_dir_name
 install_dir=${MESHERY_INSTALL_DIR}
 if [ -z "$install_dir" ]
 then
-    install_dir="/usr/local/bin"
+install_dir="/usr/local/bin"
 fi
 
 printf "\nInstalling mesheryctl in $install_dir.\n"
 WHOAMI=$(whoami)
 if mv ${PWD}/$temporary_dir_name/mesheryctl $install_dir/mesheryctl ; then
-  echo "mesheryctl installed."
+echo "mesheryctl installed."
 else
-  if sudo mv ${PWD}/$temporary_dir_name/mesheryctl $install_dir/mesheryctl ; then
+if sudo mv ${PWD}/$temporary_dir_name/mesheryctl $install_dir/mesheryctl ; then
     echo "Permission Resolved: mesheryctl installed using sudo permissions."
-  else
+else
     echo "Cannot install mesheryctl. Check permissions of $WHOAMI for $install_dir."
     exit 1
-  fi
+fi
 fi
 
 #Transfering permissions and ownership to client USER
 if [ "$SUDO_USER" == "" ] ;
 then
-	if chown $WHOAMI $install_dir/mesheryctl ; then
+if chown $WHOAMI $install_dir/mesheryctl ; then
     echo "permissions moved to "$WHOAMI
-  else
+else
     echo "Unable to write to $install_dir. Please verify write permission for $WHOAMI."
     exit 1
-  fi
+fi
 else
-	if chown $SUDO_USER /usr/local/bin/mesheryctl ; then
+if chown $SUDO_USER /usr/local/bin/mesheryctl ; then
     echo "permissions moved to "$SUDO_USER
-  else
+else
     echo "Unable to write to $install_dir/mesheryctl. Please verify write permission for $SUDO_USER."
     exit 1
-  fi
+fi
 fi
 
 
 printf "Removing installation files and opening Meshery..."
 rm -rf meshery.zip ${PWD}/$temporary_dir_name/
 
+
+# if ADAPTERS are empty then we'd use default local context else go we'd create custom context, which only fetches required adapters
+# Valid adapter option are
+# cpx
+# consul
+# istio
+# linkerd
+# nsm
+# kuma
+# cpx
+# osm
+# traefik
+
+## Any adapter other than above would be ignored
+if [ ! -z "$ADAPTERS" ]; then
+adpaterString=
+for adapter in $ADAPTERS; do
+    case $adapter in
+        cpx|consul|istio|linkerd|nsm|kuma|cpx|osm)
+            adapterString="$adapterString -a meshery-$adapter "
+        ;;
+        traefik)
+            adapterString="$adapterString -a meshery-$adapter-mesh "
+        ;;
+        *)
+            # We are just neglecting invalid mesh options
+        ;;
+    esac    
+  done
+
+    mesheryctl system context create custom -s $adapterString --yes
+fi
+
 mesheryctl system start --yes -p $PLATFORM
+
+
