testing precommit hook
Signed-off-by: suhail34 <suhailkna@gmail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,3 +8,8 @@ make error
 echo "Running make target for mesheryctl meshkit error duplicacy"
 cd mesheryctl
 make error
+
+if [ $? -ne 0 ]; then
+    echo "Aborting commit Meshkit Error Duplicacy found"
+    exit 1
+fi
